openapi: 3.0.1
info:
  title: Weather API
  description: A simple API to post and get weather data.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /weather:
    post:
      summary: Submit weather data for a specific city and day
      description: Add weather data for a city and day
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  example: "New York"
                day:
                  type: string
                  example: "26-06-2024"
      responses:
        '201':
          description: Weather data successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Weather data created successfully"
                  data:
                    type: object
                    properties:
                      city:
                        type: string
                        example: "New York"
                      day:
                        type: string
                        example: "26-06-2024"
                      min-temperature:
                        type: number
                        example: 25.3
                      max-temperature:
                        type: number
                        example: 25.3
                      avg-temperature:
                        type: number
                        example: 25.3
                      humidity:
                        type: number
                        example: 84%
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data"
    get:
      summary: Retrieve weather data for a specific city and day
      description: Get weather data if it exists for the specified city and day
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
          example: "New York"
        - name: day
          in: query
          required: true
          schema:
            type: string
          example: "26-06-2024"
      responses:
        '200':
          description: Weather data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                    example: "New York"
                  day:
                    type: string
                    example: "26-06-2024"
                  min-temperature:
                    type: number
                    example: 25.3
                  max-temperature:
                    type: number
                    example: 25.3
                  avg-temperature:
                    type: number
                    example: 25.3
                  humidity:
                    type: number
                    example: 84%
        '404':
          description: Weather data not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Weather data not found for the specified city and day"
