openapi: 3.0.1
info:
  title: Weather API
  description: A simple API to post and get weather data.
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: http://34.254.159.254:80/weather
    description: Local development server
paths:
  /weather/{city}:
    post:
      summary: Submit weather data for a specific city
      description: Add weather data for a city
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
            example: "Dublin"
      responses:
        '201':
          description: Weather data successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  http_code:
                    type: string
                    example: "201"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        city:
                          type: string
                          example: "Dublin"
                        date:
                          type: string
                          example: "2024-07-01"
                        min_temp:
                          type: string
                          example: "18.16"
                        max_temp:
                          type: string
                          example: "26.56"
                        avg_temp:
                          type: string
                          example: "22.36"
                        humidity:
                          type: string
                          example: "58"
        '400':
          description: Integrity error or Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  http_code:
                    type: string
                    example: "400"
                  data:
                    type: object
                    properties:
                      error_message:
                        type: string
                        oneOf:
                          - example: "Integrity error occurred: UNIQUE constraint failed: weather.date, weather.city"
                          - example: "Invalid request"
                      http_code:
                        type: string
                        example: "400"
        '404':
          description: City not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  http_code:
                    type: string
                    example: "404"
                  data:
                    type: object
                    properties:
                      error_message:
                        type: string
                        example: "city not found"
                      http_code:
                        type: string
                        example: "404"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  http_code:
                    type: string
                    example: "500"
                  data:
                    type: object
                    properties:
                      error_message:
                        type: string
                        example: "Internal server error"
                      http_code:
                        type: string
                        example: "500"
  /weather:
    get:
      summary: Retrieve weather data for a specific date
      description: Get weather data if it exists for the specified date
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "2024-06-29"
      responses:
        '200':
          description: Weather data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  http_code:
                    type: string
                    example: "200"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        city:
                          type: string
                          example: "London"
                        date:
                          type: string
                          example: "2024-06-29"
                        min_temp:
                          type: string
                          example: "15.5"
                        max_temp:
                          type: string
                          example: "25.0"
                        avg_temp:
                          type: string
                          example: "20.25"
                        humidity:
                          type: string
                          example: "60"
        '404':
          description: Weather data not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  http_code:
                    type: string
                    example: "404"
                  data:
                    type: object
                    properties:
                      error_message:
                        type: string
                        example: "No records found for date : 2024-06-10"
                      http_code:
                        type: string
                        example: "404"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  http_code:
                    type: string
                    example: "500"
                  data:
                    type: object
                    properties:
                      error_message:
                        type: string
                        example: "Internal server error"
                      http_code:
                        type: string
                        example: "500"
