name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to ECR
        run: | 
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 586367048044.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            TAG=main
          fi
          docker build -t ocula-weather-api .
          docker tag ocula-weather-api:latest 586367048044.dkr.ecr.eu-west-1.amazonaws.com/ocula-weather-repo:$TAG
          docker push 586367048044.dkr.ecr.eu-west-1.amazonaws.com/ocula-weather-repo:$TAG
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              TAG=prod
              HOST=${{ secrets.EC2_HOST }}

            fi
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 586367048044.dkr.ecr.eu-west-1.amazonaws.com
            docker pull 586367048044.dkr.ecr.eu-west-1.amazonaws.com/ocula-weather-repo:$TAG
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name ocula-weather-api -p 80:80 586367048044.dkr.ecr.eu-west-1.amazonaws.com/ocula-weather-repo:$TAG